# Generated by Django 4.2 on 2023-05-16 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
            },
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование пигмента')),
            ],
            options={
                'verbose_name': 'Пигмент',
                'verbose_name_plural': 'Пигменты',
            },
        ),
        migrations.CreateModel(
            name='PigmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа пигментов')),
            ],
            options={
                'verbose_name': 'Группа пигментов',
                'verbose_name_plural': 'Группы пигментов',
            },
        ),
        migrations.CreateModel(
            name='PigmentPaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование пигментной пасты')),
                ('grid', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Перетир')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время затирания')),
                ('production_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изготовления')),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.base', verbose_name='Основа')),
                ('pigment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.pigment', verbose_name='Пигмент')),
            ],
            options={
                'verbose_name': 'Пигментная паста',
                'verbose_name_plural': 'Пигментные пасты',
            },
        ),
        migrations.AddField(
            model_name='pigment',
            name='pigment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.pigmentgroup', verbose_name='Пигментная группа'),
        ),
        migrations.CreateModel(
            name='Enamel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование эмали')),
                ('colour', models.CharField(max_length=100, verbose_name='Цвет')),
                ('base', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.base', verbose_name='Основа')),
                ('pigment_paste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.pigmentpaste', verbose_name='Пигментная паста')),
            ],
            options={
                'verbose_name': 'Эмаль',
                'verbose_name_plural': 'Эмали',
            },
        ),
    ]
