# Generated by Django 4.2.1 on 2023-05-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Перетир')),
                ('filling', models.CharField(blank=True, max_length=100, null=True, verbose_name='Проверка на налив')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время анализа')),
            ],
        ),
        migrations.RemoveField(
            model_name='pigmentpaste',
            name='grid',
        ),
        migrations.AddField(
            model_name='pigmentpaste',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.analysis', verbose_name='Результаты испытаний'),
        ),
    ]
