# Generated by Django 4.2.1 on 2023-05-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_analysis_remove_pigmentpaste_grid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Результат испытаний', 'verbose_name_plural': 'Результаты испытаний'},
        ),
        migrations.RenameField(
            model_name='pigmentpaste',
            old_name='analysis',
            new_name='analyzes',
        ),
        migrations.AddField(
            model_name='analysis',
            name='sample',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.pigmentpaste', verbose_name='Образец'),
        ),
    ]
