# Generated by Django 4.2.1 on 2023-05-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_analysis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigmentpaste',
            name='time',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.pigmentpaste', verbose_name='Образец'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='Время анализа'),
        ),
        migrations.AlterField(
            model_name='pigmentpaste',
            name='analyzes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.analysis', verbose_name='Результаты испытаний'),
        ),
    ]
