# Generated by Django 4.2 on 2023-05-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_pigmentpaste_time_alter_analysis_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enamel',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.base', verbose_name='Основа'),
        ),
        migrations.AlterField(
            model_name='pigmentpaste',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.base', verbose_name='Основа'),
        ),
        migrations.AlterField(
            model_name='pigmentpaste',
            name='pigment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.pigment', verbose_name='Пигмент'),
        ),
    ]
